"""Dashboard data layer.

The Streamlit app is a thin skin over plain functions (`discover`, `load_run`,
`comparison_table`, ...). Those functions are what actually reads your files, so
they are what needs testing — no browser, no Streamlit runtime required.

The module is loaded from its path because `dashboard/` is deliberately not a
package (Streamlit runs it as a script).
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pandas as pd
import pytest

APP = Path(__file__).resolve().parents[1] / "dashboard" / "app.py"


def _load_app_module():
    spec = importlib.util.spec_from_file_location("scalper_dashboard_app", APP)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def app():
    assert APP.is_file(), "dashboard/app.py is missing"
    return _load_app_module()


@pytest.fixture
def results_dir(tmp_path: Path) -> Path:
    """A miniature `results/` directory with two runs, one of them synthetic."""
    out = tmp_path / "results"
    out.mkdir()

    def write(symbol: str, strategy: str, trades: list[dict], equity: list[tuple[str, float]],
              warnings: list[str]) -> None:
        stem = f"{symbol}_{strategy}_M1"
        metrics = {
            "net_profit": sum(t["net_pnl"] for t in trades),
            "return_pct": sum(t["net_pnl"] for t in trades) / 100.0,
            "total_trades": len(trades),
            "win_rate_pct": 50.0,
            "profit_factor": 1.25,
            "expectancy_r": 0.1,
            "max_drawdown_pct": 3.0,
            "sharpe": 0.5,
        }
        payload = {
            "symbol": symbol,
            "strategy": strategy,
            "timeframe": "M1",
            "period": {"start": equity[0][0], "end": equity[-1][0], "bars": 100, "days": 1.0},
            "account": {"initial_balance": 10_000.0, "final_balance": 10_000.0,
                        "net_profit": metrics["net_profit"]},
            "metrics": metrics,
            "engine": {"bars_processed": 100},
            "data_warnings": warnings,
        }
        (out / f"{stem}_report.json").write_text(json.dumps(payload), encoding="utf-8")
        if trades:
            pd.DataFrame(trades).to_csv(out / f"{stem}_trades.csv", index=False)
        if equity:
            pd.DataFrame(
                [{"time": t, "balance": 10_000.0, "equity": e, "unrealized": 0.0,
                  "open_positions": 0} for t, e in equity]
            ).to_csv(out / f"{stem}_equity.csv", index=False)

    trade = {
        "entry_time": "2024-01-02T09:00:00+00:00",
        "exit_time": "2024-01-02T09:20:00+00:00",
        "symbol": "EURUSD",
        "direction": "long",
        "lots": 0.5,
        "entry_price": 1.1,
        "exit_price": 1.102,
        "stop_price": 1.099,
        "take_profit_price": 1.102,
        "pips": 20.0,
        "gross_pnl": 110.0,
        "commission": 3.5,
        "net_pnl": 106.5,
        "r_multiple": 1.8,
        "exit_reason": "take_profit",
        "strategy": "ema_rsi_momentum",
        "bars_held": 20,
        "duration_minutes": 20.0,
    }
    write("EURUSD", "ema_rsi_momentum", [trade], [("2024-01-01T00:00:00+00:00", 10_000.0),
                                                 ("2024-01-31T23:59:00+00:00", 10_106.5)],
          ["SYNTHETIC DATA: bars were generated by a random process."])
    write("XAUUSD", "bollinger_reversion", [], [("2024-01-01T00:00:00+00:00", 10_000.0),
                                                ("2024-01-31T23:59:00+00:00", 9_900.0)],
          [])
    return out


def test_module_imports_without_a_streamlit_runtime(app):
    """Importing the app must have no side effects (no UI calls at module level)."""
    assert callable(app.render)
    assert callable(app.load_runs)


def test_discover_ignores_portfolio_files_and_missing_directory(app, results_dir):
    found = app.discover(results_dir)
    assert {p.name for p in found} == {"EURUSD_ema_rsi_momentum_M1_report.json",
                                       "XAUUSD_bollinger_reversion_M1_report.json"}
    (results_dir / "portfolio_20240101.csv").write_text("x", encoding="utf-8")
    (results_dir / "portfolio_20240101_report.json").write_text("{}", encoding="utf-8")
    assert len(app.discover(results_dir)) == 2
    assert app.discover(results_dir / "does-not-exist") == []


def test_load_run_pulls_in_siblings_and_flags_synthetic_data(app, results_dir):
    run = app.load_run(results_dir / "EURUSD_ema_rsi_momentum_M1_report.json")
    assert (run.symbol, run.strategy, run.timeframe) == ("EURUSD", "ema_rsi_momentum", "M1")
    assert run.label == "EURUSD · ema_rsi_momentum · M1"
    assert run.total_trades == 1
    assert run.net_profit == pytest.approx(106.5)
    assert run.is_synthetic is True
    assert run.trades is not None and len(run.trades) == 1
    # Timestamps are parsed to UTC datetimes, not left as strings, so charts work.
    assert str(run.trades["entry_time"].dtype).startswith("datetime64")
    assert run.equity is not None and len(run.equity) == 2

    other = app.load_run(results_dir / "XAUUSD_bollinger_reversion_M1_report.json")
    assert other.is_synthetic is False
    assert other.trades is None, "no trades CSV on disk -> None, not an empty crash"


def test_row_missing_files_do_not_explode(app, tmp_path):
    lone = tmp_path / "EURUSD_ema_rsi_momentum_M1_report.json"
    lone.write_text(json.dumps({"symbol": "EURUSD", "metrics": {}}), encoding="utf-8")
    run = app.load_run(lone)
    assert run.trades is None and run.equity is None
    assert run.net_profit == 0.0
    table = app.comparison_table([run])
    assert list(table["symbol"]) == ["EURUSD"]
    assert table["synthetic"].iloc[0] == False  # noqa: E712 - pandas bool, not a bool


def test_comparison_table_has_one_row_per_run(app, results_dir):
    runs = app.load_runs(results_dir)
    table = app.comparison_table(runs)
    assert len(table) == 2
    assert set(table["symbol"]) == {"EURUSD", "XAUUSD"}
    assert table["net_profit"].sum() == pytest.approx(106.5)
    assert list(table.columns)[:4] == ["symbol", "strategy", "timeframe", "trades"]


def test_equity_frame_stacks_runs_for_charting(app, results_dir):
    runs = app.load_runs(results_dir)
    frame = app.equity_frame(runs)
    assert set(frame["run"]) == {r.label for r in runs}
    assert frame["time"].is_monotonic_increasing is False or True  # order is not promised
    assert len(frame) == 4
    assert app.equity_frame([]).empty


def test_monthly_returns_frame_uses_each_runs_own_start(app, results_dir):
    runs = app.load_runs(results_dir)
    frame = app.monthly_returns_frame(runs)
    assert set(frame["period"]) == {"2024-01"}
    eur = frame[frame["run"].str.startswith("EURUSD")].iloc[0]
    xau = frame[frame["run"].str.startswith("XAUUSD")].iloc[0]
    assert eur["return_pct"] == pytest.approx(1.065, abs=0.01)   # 10,000 -> 10,106.50
    assert xau["return_pct"] == pytest.approx(-1.0, abs=0.01)    # 10,000 -> 9,900
    assert app.monthly_returns_frame([]).empty


def test_broken_json_degrades_instead_of_raising(app, tmp_path):
    bad = tmp_path / "EURUSD_ema_rsi_momentum_M1_report.json"
    bad.write_text("{not json at all", encoding="utf-8")
    run = app.load_run(bad)
    assert run.metrics == {} and run.net_profit == 0.0


# --------------------------------------------------------------------------- #
# CLI wiring: `scalper dashboard`
# --------------------------------------------------------------------------- #
def test_cli_dashboard_explains_the_extra_when_streamlit_is_absent(monkeypatch, capsys):
    """A missing optional dependency must produce instructions, not a traceback."""
    import importlib.util as util

    from scalper import cli

    real_find_spec = util.find_spec
    monkeypatch.setattr(
        util, "find_spec", lambda name, *a, **k: None if name == "streamlit" else real_find_spec(name, *a, **k)
    )
    code = cli.main(["dashboard"])
    assert code == 2
    err = capsys.readouterr().err
    assert "streamlit" in err.lower()
    assert "pip install" in err


def test_cli_dashboard_launches_streamlit_against_the_app(monkeypatch, tmp_path, capsys):
    """The command must shell out to `streamlit run dashboard/app.py` and pass the port."""
    from scalper import cli

    captured: dict = {}

    def fake_call(argv, *a, **k):
        captured["argv"] = argv
        return 0

    monkeypatch.setattr("subprocess.call", fake_call)
    code = cli.main(["dashboard", "--port", "8601", "--address", "127.0.0.1"])
    assert code == 0
    argv = captured["argv"]
    assert argv[1:5] == ["-m", "streamlit", "run", str(APP)]
    assert "--server.port" in argv and "8601" in argv
    assert "--server.address" in argv and "127.0.0.1" in argv
    assert "http://localhost:8601" in capsys.readouterr().out


def test_cli_dashboard_reports_a_missing_app_file(monkeypatch, tmp_path, capsys):
    from scalper import cli

    monkeypatch.setattr("subprocess.call", lambda *a, **k: pytest.fail("should not launch"))
    monkeypatch.setattr(cli.Path, "is_file", lambda self: False)
    code = cli.main(["dashboard"])
    assert code == 2
    assert "not found" in capsys.readouterr().err
