"""Go-live readiness gates.

These tests care about one property above all: the checklist must refuse to say
"ready" for the situations people actually get into — synthetic data, three
trades, a bull month, or one lucky symbol out of five.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from scalper.config import load_config
from scalper.readiness import (
    FAIL,
    PASS,
    WARN,
    assess_readiness,
    format_report,
    load_result_summaries,
)

SYNTHETIC_WARNING = "SYNTHETIC DATA: bars were generated by a random process, not taken from the market."


@pytest.fixture
def cfg(tmp_path):
    config = load_config("config/config.yaml")
    config.reporting.output_dir = str(tmp_path / "results")
    return config


def write_run(
    directory: Path,
    symbol: str,
    *,
    trades: int = 150,
    expectancy_r: float = 0.10,
    profit_factor: float = 1.40,
    days: float = 700.0,
    max_drawdown_pct: float = 4.0,
    synthetic: bool = False,
    strategy: str = "ema_rsi_momentum",
) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    payload = {
        "symbol": symbol,
        "strategy": strategy,
        "timeframe": "M1",
        "period": {"start": "2023-01-01T00:00:00+00:00", "end": "2024-12-01T00:00:00+00:00",
                   "bars": trades * 100, "days": days},
        "account": {"initial_balance": 10_000.0, "final_balance": 10_000.0 + trades * expectancy_r},
        "metrics": {
            "net_profit": trades * expectancy_r * 50,
            "total_trades": trades,
            "expectancy_r": expectancy_r,
            "profit_factor": profit_factor,
            "max_drawdown_pct": max_drawdown_pct,
        },
        "engine": {},
        "data_warnings": [SYNTHETIC_WARNING] if synthetic else [],
    }
    path = directory / f"{symbol}_{strategy}_M1_report.json"
    path.write_text(json.dumps(payload), encoding="utf-8")
    return path


def status_of(report, key: str) -> str:
    return next(c.status for c in report.checks if c.key == key)


# --------------------------------------------------------------------------- #
# The honest cases
# --------------------------------------------------------------------------- #
def test_no_results_is_a_clean_failure_not_a_crash(cfg):
    report = assess_readiness(cfg)
    assert report.verdict == "NOT READY"
    assert status_of(report, "results") is FAIL
    assert "backtest" in report.next_action()
    # With nothing on disk only two gates can be judged: "there is no evidence"
    # and "live routing is off". The rest are withheld rather than printed as ten
    # near-identical failures, and the report says so.
    assert {c.key for c in report.checks} == {"results", "gates"}
    assert status_of(report, "gates") is PASS, "switched-off live routing is a pass regardless"
    assert "not shown" in next(c.detail for c in report.checks if c.key == "results")


def test_synthetic_data_can_never_pass_even_if_the_numbers_are_beautiful(cfg, tmp_path):
    """The single most important rule: favourable randomness is not evidence."""
    for symbol in ("EURUSD", "GBPUSD", "XAUUSD"):
        write_run(tmp_path / "results", symbol, synthetic=True)
    report = assess_readiness(cfg)
    assert status_of(report, "data") is FAIL
    assert report.verdict == "NOT READY"
    assert "real M1 history" in report.next_action()


def test_a_negative_result_is_reported_as_a_negative_result(cfg, tmp_path):
    for symbol, exp in (("EURUSD", -0.20), ("GBPUSD", -0.27), ("XAUUSD", -0.14)):
        write_run(tmp_path / "results", symbol, expectancy_r=exp, profit_factor=0.6)
    report = assess_readiness(cfg)
    assert status_of(report, "expectancy") is FAIL
    assert status_of(report, "pf") is FAIL
    assert status_of(report, "consistency") is FAIL
    assert "Do not deploy" in report.next_action()
    assert report.verdict == "NOT READY"


def test_thin_sample_is_a_failure_not_a_pass(cfg, tmp_path):
    write_run(tmp_path / "results", "EURUSD", trades=7, days=20)
    report = assess_readiness(cfg)
    assert status_of(report, "trades") is FAIL
    assert status_of(report, "span") is FAIL


def test_one_lucky_symbol_out_of_five_is_not_an_edge(cfg, tmp_path):
    """Gating on the best run is how people ship losers."""
    write_run(tmp_path / "results", "XAUUSD", expectancy_r=0.55, profit_factor=2.2)
    for symbol in ("EURUSD", "GBPUSD", "USDJPY", "AUDUSD"):
        write_run(tmp_path / "results", symbol, expectancy_r=-0.15, profit_factor=0.7)
    report = assess_readiness(cfg)
    assert status_of(report, "consistency") is WARN
    assert "as likely to be that symbol's month" in next(
        c.detail for c in report.checks if c.key == "consistency"
    )
    # Four losers drag the median below zero, which is a failure, not a warning:
    # one good symbol out of five is a coincidence with good press.
    assert status_of(report, "expectancy") is FAIL
    assert report.verdict == "NOT READY"


def test_median_expectancy_ignores_one_spectacular_run(cfg, tmp_path):
    write_run(tmp_path / "results", "XAUUSD", expectancy_r=5.0, profit_factor=9.0)
    write_run(tmp_path / "results", "EURUSD", expectancy_r=-0.30, profit_factor=0.5)
    write_run(tmp_path / "results", "GBPUSD", expectancy_r=-0.10, profit_factor=0.8)
    report = assess_readiness(cfg)
    # The median is negative, so no amount of one good symbol rescues the verdict.
    assert status_of(report, "expectancy") is FAIL
    assert report.verdict == "NOT READY"


def test_nothing_is_ready_while_live_routing_is_armed_around_a_failing_strategy(cfg, tmp_path, monkeypatch):
    write_run(tmp_path / "results", "EURUSD", expectancy_r=-0.2, profit_factor=0.5)
    monkeypatch.setenv("SCALPER_ALLOW_LIVE", "yes")
    cfg.broker.mode = "mt5"
    report = assess_readiness(cfg)
    assert status_of(report, "gates") is WARN
    assert report.verdict == "NOT READY"


# --------------------------------------------------------------------------- #
# The case where the answer changes
# --------------------------------------------------------------------------- #
def test_real_data_with_a_consistent_edge_can_pass(cfg, tmp_path):
    results = tmp_path / "results"
    for symbol in ("EURUSD", "GBPUSD", "XAUUSD"):
        write_run(results, symbol, expectancy_r=0.08, profit_factor=1.5, days=800)
    (results / "sweep_20240101_120000.csv").write_text("fast_ema,expectancy_r\n9,0.08\n", encoding="utf-8")
    report = assess_readiness(cfg)
    assert report.failures == []
    assert report.warnings == [], [c.detail for c in report.warnings]
    assert report.verdict.startswith("READY")
    # Even a pass keeps the disclaimer: a checklist is not a forecast.
    assert "not a prediction" in report.disclaimer
    assert "forecast" not in report.disclaimer.split("It is")[0]


def test_missing_out_of_sample_evidence_blocks_a_full_pass(cfg, tmp_path):
    for symbol in ("EURUSD", "GBPUSD"):
        write_run(tmp_path / "results", symbol, expectancy_r=0.08, profit_factor=1.5, days=800)
    report = assess_readiness(cfg)
    assert status_of(report, "oos") is WARN
    assert report.verdict == "PROBABLY NOT READY"
    assert "optimize.py" in report.next_action()


def test_drawdown_overshoot_is_called_out(cfg, tmp_path):
    write_run(tmp_path / "results", "EURUSD", max_drawdown_pct=12.3)
    write_run(tmp_path / "results", "GBPUSD", max_drawdown_pct=4.0)
    report = assess_readiness(cfg)
    assert status_of(report, "dd") is WARN
    assert "overshoot" in next(c.detail for c in report.checks if c.key == "dd")


# --------------------------------------------------------------------------- #
# Plumbing
# --------------------------------------------------------------------------- #
def test_load_summaries_skips_the_aggregate_and_survives_broken_files(cfg, tmp_path):
    results = tmp_path / "results"
    write_run(results, "EURUSD")
    (results / "portfolio_20240101_120000_report.json").write_text("{}", encoding="utf-8")
    (results / "BROKEN_report.json").write_text("{not json", encoding="utf-8")
    summaries = load_result_summaries(results)
    assert [s["symbol"] for s in summaries] == ["EURUSD"]
    assert load_result_summaries(results / "missing") == []


def test_report_renders_and_serialises(cfg, tmp_path):
    for symbol in ("EURUSD", "GBPUSD", "XAUUSD"):
        write_run(tmp_path / "results", symbol, synthetic=True)
    report = assess_readiness(cfg)
    text = format_report(report)
    assert "NOT READY" in text and "Go-live readiness" in text
    payload = report.to_dict()
    assert payload["verdict"] == "NOT READY"
    assert payload["counts"]["fail"] >= 1
    assert json.dumps(payload)  # must be serialisable for --json
    assert set(payload["checks"][0]) == {"key", "label", "status", "detail", "fix"}


def test_cli_readiness_reports_and_exits_nonzero_while_blocked(cfg, tmp_path, capsys, monkeypatch):
    from scalper import cli

    for symbol in ("EURUSD", "GBPUSD"):
        write_run(tmp_path / "results", symbol, synthetic=True, expectancy_r=-0.2)
    code = cli.main(["readiness", "--results-dir", str(tmp_path / "results")])
    assert code == 1, "a blocked deployment must be a non-zero exit for scripts"
    out = capsys.readouterr().out
    assert "NOT READY" in out and "[FAIL]" in out


def test_cli_readiness_exits_zero_when_every_gate_passes(cfg, tmp_path, capsys):
    from scalper import cli

    results = tmp_path / "results"
    for symbol in ("EURUSD", "GBPUSD", "XAUUSD"):
        write_run(results, symbol, expectancy_r=0.08, profit_factor=1.5, days=800)
    (results / "sweep_x.csv").write_text("a\n1\n", encoding="utf-8")
    code = cli.main(["readiness", "--results-dir", str(results), "--json"])
    assert code == 0
    out = capsys.readouterr().out
    assert "READY" in out and '"verdict"' in out
