"""initial schema

Revision ID: 4bfd2e3d1d1c
Revises: 
Create Date: 2026-09-19 16:34:11.925972

"""
from alembic import op
import sqlalchemy as sa


revision = '4bfd2e3d1d1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_snapshots',
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('free_margin', sa.Float(), nullable=False),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_ts'), 'account_snapshots', ['ts'], unique=False)
    op.create_index('ix_snapshots_account_ts', 'account_snapshots', ['account_id', 'ts'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('trading_paused', sa.Boolean(), nullable=False),
    sa.Column('kill_reason', sa.Text(), nullable=True),
    sa.Column('pause_reason', sa.Text(), nullable=True),
    sa.Column('risk_config', sa.JSON(), nullable=False),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candles',
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('timeframe_s', sa.Integer(), nullable=False),
    sa.Column('ts_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume_ticks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument', 'timeframe_s', 'ts_open', name='uq_candle')
    )
    op.create_index(op.f('ix_candles_instrument'), 'candles', ['instrument'], unique=False)
    op.create_index('ix_candles_lookup', 'candles', ['instrument', 'timeframe_s', 'ts_open'], unique=False)
    op.create_index(op.f('ix_candles_timeframe_s'), 'candles', ['timeframe_s'], unique=False)
    op.create_index(op.f('ix_candles_ts'), 'candles', ['ts'], unique=False)
    op.create_table('order_journal',
    sa.Column('order_uid', sa.String(length=40), nullable=False),
    sa.Column('client_request_id', sa.String(length=128), nullable=False),
    sa.Column('operation_id', sa.String(length=32), nullable=True),
    sa.Column('broker', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('price_requested', sa.Float(), nullable=True),
    sa.Column('price_filled', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('slippage', sa.Float(), nullable=True),
    sa.Column('spread_at_entry', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_journal_client_request_id'), 'order_journal', ['client_request_id'], unique=True)
    op.create_index(op.f('ix_order_journal_instrument'), 'order_journal', ['instrument'], unique=False)
    op.create_index(op.f('ix_order_journal_order_uid'), 'order_journal', ['order_uid'], unique=True)
    op.create_index(op.f('ix_order_journal_state'), 'order_journal', ['state'], unique=False)
    op.create_index(op.f('ix_order_journal_ts'), 'order_journal', ['ts'], unique=False)
    op.create_table('risk_events',
    sa.Column('rule', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('order_uid', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_events_rule'), 'risk_events', ['rule'], unique=False)
    op.create_index(op.f('ix_risk_events_ts'), 'risk_events', ['ts'], unique=False)
    op.create_table('system_logs',
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_source'), 'system_logs', ['source'], unique=False)
    op.create_index(op.f('ix_system_logs_ts'), 'system_logs', ['ts'], unique=False)
    op.create_table('trades',
    sa.Column('order_uid', sa.String(length=40), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('entry_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('costs', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.Column('execution_status', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_entry_ts'), 'trades', ['entry_ts'], unique=False)
    op.create_index(op.f('ix_trades_instrument'), 'trades', ['instrument'], unique=False)
    op.create_index(op.f('ix_trades_order_uid'), 'trades', ['order_uid'], unique=True)
    op.create_index(op.f('ix_trades_strategy'), 'trades', ['strategy'], unique=False)
    op.create_index(op.f('ix_trades_ts'), 'trades', ['ts'], unique=False)
    op.create_table('signals',
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.Column('ai_recommendation', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_instrument'), 'signals', ['instrument'], unique=False)
    op.create_index('ix_signals_instrument_ts', 'signals', ['instrument', 'ts'], unique=False)
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_strategy'), 'signals', ['strategy'], unique=False)
    op.create_index(op.f('ix_signals_ts'), 'signals', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_ts'), table_name='signals')
    op.drop_index(op.f('ix_signals_strategy'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_index('ix_signals_instrument_ts', table_name='signals')
    op.drop_index(op.f('ix_signals_instrument'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_trades_ts'), table_name='trades')
    op.drop_index(op.f('ix_trades_strategy'), table_name='trades')
    op.drop_index(op.f('ix_trades_order_uid'), table_name='trades')
    op.drop_index(op.f('ix_trades_instrument'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_ts'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_system_logs_ts'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_source'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_risk_events_ts'), table_name='risk_events')
    op.drop_index(op.f('ix_risk_events_rule'), table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index(op.f('ix_order_journal_ts'), table_name='order_journal')
    op.drop_index(op.f('ix_order_journal_state'), table_name='order_journal')
    op.drop_index(op.f('ix_order_journal_order_uid'), table_name='order_journal')
    op.drop_index(op.f('ix_order_journal_instrument'), table_name='order_journal')
    op.drop_index(op.f('ix_order_journal_client_request_id'), table_name='order_journal')
    op.drop_table('order_journal')
    op.drop_index(op.f('ix_candles_ts'), table_name='candles')
    op.drop_index(op.f('ix_candles_timeframe_s'), table_name='candles')
    op.drop_index('ix_candles_lookup', table_name='candles')
    op.drop_index(op.f('ix_candles_instrument'), table_name='candles')
    op.drop_table('candles')
    op.drop_table('app_settings')
    op.drop_index('ix_snapshots_account_ts', table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_ts'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    # ### end Alembic commands ###
